# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto;
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal.proto;',
  package='signal',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsignal.proto;\x12\x06signal\"J\n\nMetaSignal\x12\x13\n\x0bticket_name\x18\x01 \x01(\t\x12\'\n\x0b\x62\x61se_signal\x18\x02 \x01(\x0b\x32\x12.signal.BaseSignal\"7\n\nBaseSignal\x12)\n\x0cprice_signal\x18\x01 \x01(\x0b\x32\x13.signal.PriceSignal\"2\n\x0bPriceSignal\x12#\n\tprice_ema\x18\x01 \x03(\x0b\x32\x10.signal.PriceEma\"%\n\x08PriceEma\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x05\x12\x0b\n\x03\x65ma\x18\x02 \x01(\x01'
)




_METASIGNAL = _descriptor.Descriptor(
  name='MetaSignal',
  full_name='signal.MetaSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_name', full_name='signal.MetaSignal.ticket_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_signal', full_name='signal.MetaSignal.base_signal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=99,
)


_BASESIGNAL = _descriptor.Descriptor(
  name='BaseSignal',
  full_name='signal.BaseSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price_signal', full_name='signal.BaseSignal.price_signal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=156,
)


_PRICESIGNAL = _descriptor.Descriptor(
  name='PriceSignal',
  full_name='signal.PriceSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price_ema', full_name='signal.PriceSignal.price_ema', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=208,
)


_PRICEEMA = _descriptor.Descriptor(
  name='PriceEma',
  full_name='signal.PriceEma',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='signal.PriceEma.date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ema', full_name='signal.PriceEma.ema', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=247,
)

_METASIGNAL.fields_by_name['base_signal'].message_type = _BASESIGNAL
_BASESIGNAL.fields_by_name['price_signal'].message_type = _PRICESIGNAL
_PRICESIGNAL.fields_by_name['price_ema'].message_type = _PRICEEMA
DESCRIPTOR.message_types_by_name['MetaSignal'] = _METASIGNAL
DESCRIPTOR.message_types_by_name['BaseSignal'] = _BASESIGNAL
DESCRIPTOR.message_types_by_name['PriceSignal'] = _PRICESIGNAL
DESCRIPTOR.message_types_by_name['PriceEma'] = _PRICEEMA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaSignal = _reflection.GeneratedProtocolMessageType('MetaSignal', (_message.Message,), {
  'DESCRIPTOR' : _METASIGNAL,
  '__module__' : 'signal.proto;_pb2'
  # @@protoc_insertion_point(class_scope:signal.MetaSignal)
  })
_sym_db.RegisterMessage(MetaSignal)

BaseSignal = _reflection.GeneratedProtocolMessageType('BaseSignal', (_message.Message,), {
  'DESCRIPTOR' : _BASESIGNAL,
  '__module__' : 'signal.proto;_pb2'
  # @@protoc_insertion_point(class_scope:signal.BaseSignal)
  })
_sym_db.RegisterMessage(BaseSignal)

PriceSignal = _reflection.GeneratedProtocolMessageType('PriceSignal', (_message.Message,), {
  'DESCRIPTOR' : _PRICESIGNAL,
  '__module__' : 'signal.proto;_pb2'
  # @@protoc_insertion_point(class_scope:signal.PriceSignal)
  })
_sym_db.RegisterMessage(PriceSignal)

PriceEma = _reflection.GeneratedProtocolMessageType('PriceEma', (_message.Message,), {
  'DESCRIPTOR' : _PRICEEMA,
  '__module__' : 'signal.proto;_pb2'
  # @@protoc_insertion_point(class_scope:signal.PriceEma)
  })
_sym_db.RegisterMessage(PriceEma)


# @@protoc_insertion_point(module_scope)
