# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal.proto',
  package='signal',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csignal.proto\x12\x06signal\"\x9f\x01\n\nMetaSignal\x12\x13\n\x0bticket_name\x18\x01 \x01(\t\x12\'\n\x0b\x62\x61se_signal\x18\x02 \x01(\x0b\x32\x12.signal.BaseSignal\x12\x1d\n\x06trends\x18\x03 \x03(\x0b\x32\r.signal.Trend\x12\x34\n\x12\x66lucturation_range\x18\x04 \x03(\x0b\x32\x18.signal.FluctuationRange\"d\n\nBaseSignal\x12)\n\x0cprice_signal\x18\x01 \x01(\x0b\x32\x13.signal.PriceSignal\x12+\n\rvalumn_signal\x18\x02 \x01(\x0b\x32\x14.signal.ValumnSignal\"2\n\x0bPriceSignal\x12#\n\tprice_ema\x18\x01 \x03(\x0b\x32\x10.signal.PriceEma\"%\n\x08PriceEma\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x05\x12\x0b\n\x03\x65ma\x18\x02 \x01(\x01\"a\n\x0cValumnSignal\x12\x14\n\nraw_valumn\x18\x01 \x01(\x01H\x00\x12\x31\n\x11normalized_valumn\x18\x02 \x01(\x0b\x32\x14.signal.NormIntervalH\x00\x42\x08\n\x06valumn\"-\n\x0eStaticInterval\x12\r\n\x05\x66loor\x18\x01 \x01(\x01\x12\x0c\n\x04\x63\x65il\x18\x02 \x01(\x01\"0\n\x0cNormInterval\x12\r\n\x05pivot\x18\x01 \x01(\x01\x12\x11\n\tdeviation\x18\x02 \x01(\x01\"\xc4\x01\n\x05Trend\x12/\n\x04type\x18\x01 \x01(\x0e\x32\x17.signal.Trend.TrendType:\x08NO_TREND\x12(\n\nconfidence\x18\x02 \x01(\x0b\x32\x14.signal.NormInterval\x12\x16\n\x0e\x65xtreme_points\x18\x03 \x03(\x01\"H\n\tTrendType\x12\x0c\n\x08NO_TREND\x10\x00\x12\x0f\n\x0b\x46luctuation\x10\x01\x12\x06\n\x02UP\x10\x02\x12\x08\n\x04\x44OWN\x10\x03\x12\n\n\x06STATIC\x10\x04\"\xf1\x01\n\x10\x46luctuationRange\x12\x34\n\x12static_floor_range\x18\x01 \x01(\x0b\x32\x16.signal.StaticIntervalH\x00\x12\x30\n\x10norm_floor_range\x18\x02 \x01(\x0b\x32\x14.signal.NormIntervalH\x00\x12\x33\n\x11static_ceil_range\x18\x03 \x01(\x0b\x32\x16.signal.StaticIntervalH\x01\x12/\n\x0fnorm_ceil_range\x18\x04 \x01(\x0b\x32\x14.signal.NormIntervalH\x01\x42\x07\n\x05\x66loorB\x06\n\x04\x63\x65il'
)



_TREND_TRENDTYPE = _descriptor.EnumDescriptor(
  name='TrendType',
  full_name='signal.Trend.TrendType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_TREND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Fluctuation', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATIC', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=700,
  serialized_end=772,
)
_sym_db.RegisterEnumDescriptor(_TREND_TRENDTYPE)


_METASIGNAL = _descriptor.Descriptor(
  name='MetaSignal',
  full_name='signal.MetaSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_name', full_name='signal.MetaSignal.ticket_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_signal', full_name='signal.MetaSignal.base_signal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trends', full_name='signal.MetaSignal.trends', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flucturation_range', full_name='signal.MetaSignal.flucturation_range', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=184,
)


_BASESIGNAL = _descriptor.Descriptor(
  name='BaseSignal',
  full_name='signal.BaseSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price_signal', full_name='signal.BaseSignal.price_signal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valumn_signal', full_name='signal.BaseSignal.valumn_signal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=286,
)


_PRICESIGNAL = _descriptor.Descriptor(
  name='PriceSignal',
  full_name='signal.PriceSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price_ema', full_name='signal.PriceSignal.price_ema', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=338,
)


_PRICEEMA = _descriptor.Descriptor(
  name='PriceEma',
  full_name='signal.PriceEma',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='signal.PriceEma.date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ema', full_name='signal.PriceEma.ema', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=377,
)


_VALUMNSIGNAL = _descriptor.Descriptor(
  name='ValumnSignal',
  full_name='signal.ValumnSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_valumn', full_name='signal.ValumnSignal.raw_valumn', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normalized_valumn', full_name='signal.ValumnSignal.normalized_valumn', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='valumn', full_name='signal.ValumnSignal.valumn',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=379,
  serialized_end=476,
)


_STATICINTERVAL = _descriptor.Descriptor(
  name='StaticInterval',
  full_name='signal.StaticInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='floor', full_name='signal.StaticInterval.floor', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ceil', full_name='signal.StaticInterval.ceil', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=523,
)


_NORMINTERVAL = _descriptor.Descriptor(
  name='NormInterval',
  full_name='signal.NormInterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pivot', full_name='signal.NormInterval.pivot', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deviation', full_name='signal.NormInterval.deviation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=573,
)


_TREND = _descriptor.Descriptor(
  name='Trend',
  full_name='signal.Trend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='signal.Trend.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='signal.Trend.confidence', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extreme_points', full_name='signal.Trend.extreme_points', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TREND_TRENDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=772,
)


_FLUCTUATIONRANGE = _descriptor.Descriptor(
  name='FluctuationRange',
  full_name='signal.FluctuationRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='static_floor_range', full_name='signal.FluctuationRange.static_floor_range', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='norm_floor_range', full_name='signal.FluctuationRange.norm_floor_range', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='static_ceil_range', full_name='signal.FluctuationRange.static_ceil_range', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='norm_ceil_range', full_name='signal.FluctuationRange.norm_ceil_range', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='floor', full_name='signal.FluctuationRange.floor',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='ceil', full_name='signal.FluctuationRange.ceil',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=775,
  serialized_end=1016,
)

_METASIGNAL.fields_by_name['base_signal'].message_type = _BASESIGNAL
_METASIGNAL.fields_by_name['trends'].message_type = _TREND
_METASIGNAL.fields_by_name['flucturation_range'].message_type = _FLUCTUATIONRANGE
_BASESIGNAL.fields_by_name['price_signal'].message_type = _PRICESIGNAL
_BASESIGNAL.fields_by_name['valumn_signal'].message_type = _VALUMNSIGNAL
_PRICESIGNAL.fields_by_name['price_ema'].message_type = _PRICEEMA
_VALUMNSIGNAL.fields_by_name['normalized_valumn'].message_type = _NORMINTERVAL
_VALUMNSIGNAL.oneofs_by_name['valumn'].fields.append(
  _VALUMNSIGNAL.fields_by_name['raw_valumn'])
_VALUMNSIGNAL.fields_by_name['raw_valumn'].containing_oneof = _VALUMNSIGNAL.oneofs_by_name['valumn']
_VALUMNSIGNAL.oneofs_by_name['valumn'].fields.append(
  _VALUMNSIGNAL.fields_by_name['normalized_valumn'])
_VALUMNSIGNAL.fields_by_name['normalized_valumn'].containing_oneof = _VALUMNSIGNAL.oneofs_by_name['valumn']
_TREND.fields_by_name['type'].enum_type = _TREND_TRENDTYPE
_TREND.fields_by_name['confidence'].message_type = _NORMINTERVAL
_TREND_TRENDTYPE.containing_type = _TREND
_FLUCTUATIONRANGE.fields_by_name['static_floor_range'].message_type = _STATICINTERVAL
_FLUCTUATIONRANGE.fields_by_name['norm_floor_range'].message_type = _NORMINTERVAL
_FLUCTUATIONRANGE.fields_by_name['static_ceil_range'].message_type = _STATICINTERVAL
_FLUCTUATIONRANGE.fields_by_name['norm_ceil_range'].message_type = _NORMINTERVAL
_FLUCTUATIONRANGE.oneofs_by_name['floor'].fields.append(
  _FLUCTUATIONRANGE.fields_by_name['static_floor_range'])
_FLUCTUATIONRANGE.fields_by_name['static_floor_range'].containing_oneof = _FLUCTUATIONRANGE.oneofs_by_name['floor']
_FLUCTUATIONRANGE.oneofs_by_name['floor'].fields.append(
  _FLUCTUATIONRANGE.fields_by_name['norm_floor_range'])
_FLUCTUATIONRANGE.fields_by_name['norm_floor_range'].containing_oneof = _FLUCTUATIONRANGE.oneofs_by_name['floor']
_FLUCTUATIONRANGE.oneofs_by_name['ceil'].fields.append(
  _FLUCTUATIONRANGE.fields_by_name['static_ceil_range'])
_FLUCTUATIONRANGE.fields_by_name['static_ceil_range'].containing_oneof = _FLUCTUATIONRANGE.oneofs_by_name['ceil']
_FLUCTUATIONRANGE.oneofs_by_name['ceil'].fields.append(
  _FLUCTUATIONRANGE.fields_by_name['norm_ceil_range'])
_FLUCTUATIONRANGE.fields_by_name['norm_ceil_range'].containing_oneof = _FLUCTUATIONRANGE.oneofs_by_name['ceil']
DESCRIPTOR.message_types_by_name['MetaSignal'] = _METASIGNAL
DESCRIPTOR.message_types_by_name['BaseSignal'] = _BASESIGNAL
DESCRIPTOR.message_types_by_name['PriceSignal'] = _PRICESIGNAL
DESCRIPTOR.message_types_by_name['PriceEma'] = _PRICEEMA
DESCRIPTOR.message_types_by_name['ValumnSignal'] = _VALUMNSIGNAL
DESCRIPTOR.message_types_by_name['StaticInterval'] = _STATICINTERVAL
DESCRIPTOR.message_types_by_name['NormInterval'] = _NORMINTERVAL
DESCRIPTOR.message_types_by_name['Trend'] = _TREND
DESCRIPTOR.message_types_by_name['FluctuationRange'] = _FLUCTUATIONRANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaSignal = _reflection.GeneratedProtocolMessageType('MetaSignal', (_message.Message,), {
  'DESCRIPTOR' : _METASIGNAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.MetaSignal)
  })
_sym_db.RegisterMessage(MetaSignal)

BaseSignal = _reflection.GeneratedProtocolMessageType('BaseSignal', (_message.Message,), {
  'DESCRIPTOR' : _BASESIGNAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.BaseSignal)
  })
_sym_db.RegisterMessage(BaseSignal)

PriceSignal = _reflection.GeneratedProtocolMessageType('PriceSignal', (_message.Message,), {
  'DESCRIPTOR' : _PRICESIGNAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.PriceSignal)
  })
_sym_db.RegisterMessage(PriceSignal)

PriceEma = _reflection.GeneratedProtocolMessageType('PriceEma', (_message.Message,), {
  'DESCRIPTOR' : _PRICEEMA,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.PriceEma)
  })
_sym_db.RegisterMessage(PriceEma)

ValumnSignal = _reflection.GeneratedProtocolMessageType('ValumnSignal', (_message.Message,), {
  'DESCRIPTOR' : _VALUMNSIGNAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.ValumnSignal)
  })
_sym_db.RegisterMessage(ValumnSignal)

StaticInterval = _reflection.GeneratedProtocolMessageType('StaticInterval', (_message.Message,), {
  'DESCRIPTOR' : _STATICINTERVAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.StaticInterval)
  })
_sym_db.RegisterMessage(StaticInterval)

NormInterval = _reflection.GeneratedProtocolMessageType('NormInterval', (_message.Message,), {
  'DESCRIPTOR' : _NORMINTERVAL,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.NormInterval)
  })
_sym_db.RegisterMessage(NormInterval)

Trend = _reflection.GeneratedProtocolMessageType('Trend', (_message.Message,), {
  'DESCRIPTOR' : _TREND,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.Trend)
  })
_sym_db.RegisterMessage(Trend)

FluctuationRange = _reflection.GeneratedProtocolMessageType('FluctuationRange', (_message.Message,), {
  'DESCRIPTOR' : _FLUCTUATIONRANGE,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.FluctuationRange)
  })
_sym_db.RegisterMessage(FluctuationRange)


# @@protoc_insertion_point(module_scope)
