# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='strategy.proto',
  package='strategy',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0estrategy.proto\x12\x08strategy\"\xc7\x01\n\x06\x41\x63tion\x12;\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32\x1b.strategy.Action.ActionType:\tNO_ACTION\x12\x32\n\x0c\x61\x63tion_value\x18\x02 \x01(\x0b\x32\x1c.strategy.Action.ActionValue\x1a\x1c\n\x0b\x41\x63tionValue\x12\r\n\x05share\x18\x01 \x01(\x01\".\n\nActionType\x12\r\n\tNO_ACTION\x10\x00\x12\x07\n\x03\x42UY\x10\x01\x12\x08\n\x04SELL\x10\x02\"=\n\tOperation\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12 \n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x10.strategy.Action'
)



_ACTION_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='strategy.Action.ActionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ACTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SELL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=182,
  serialized_end=228,
)
_sym_db.RegisterEnumDescriptor(_ACTION_ACTIONTYPE)


_ACTION_ACTIONVALUE = _descriptor.Descriptor(
  name='ActionValue',
  full_name='strategy.Action.ActionValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='share', full_name='strategy.Action.ActionValue.share', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=180,
)

_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='strategy.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_type', full_name='strategy.Action.action_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_value', full_name='strategy.Action.action_value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ACTION_ACTIONVALUE, ],
  enum_types=[
    _ACTION_ACTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=228,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='strategy.Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticker', full_name='strategy.Operation.ticker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='strategy.Operation.action', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=291,
)

_ACTION_ACTIONVALUE.containing_type = _ACTION
_ACTION.fields_by_name['action_type'].enum_type = _ACTION_ACTIONTYPE
_ACTION.fields_by_name['action_value'].message_type = _ACTION_ACTIONVALUE
_ACTION_ACTIONTYPE.containing_type = _ACTION
_OPERATION.fields_by_name['action'].message_type = _ACTION
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {

  'ActionValue' : _reflection.GeneratedProtocolMessageType('ActionValue', (_message.Message,), {
    'DESCRIPTOR' : _ACTION_ACTIONVALUE,
    '__module__' : 'strategy_pb2'
    # @@protoc_insertion_point(class_scope:strategy.Action.ActionValue)
    })
  ,
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'strategy_pb2'
  # @@protoc_insertion_point(class_scope:strategy.Action)
  })
_sym_db.RegisterMessage(Action)
_sym_db.RegisterMessage(Action.ActionValue)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'strategy_pb2'
  # @@protoc_insertion_point(class_scope:strategy.Operation)
  })
_sym_db.RegisterMessage(Operation)


# @@protoc_insertion_point(module_scope)
